apiVersion: v1
kind: Namespace
metadata:
  name: cnfde9-cluster
---
apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  labels:
    cloud: auto-detect
    vendor: auto-detect
    name: cnfde9-cluster
    profile: du
    hardwareType: dell
  name: cnfde9-cluster
spec:
  hubAcceptsClient: true
---
apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: cnfde9-cluster
  namespace: cnfde9-cluster
spec:
  clusterName: cnfde9-cluster
  clusterNamespace: cnfde9-cluster
  clusterLabels:
    cloud: auto-detect
    vendor: auto-detect
  applicationManager:
    enabled: true
  policyController:
    enabled: true
  searchCollector:
    enabled: true
  certPolicyController:
    enabled: true
  iamPolicyController:
    enabled: true
  version: 2.1.0
