apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 04_sriov_network_node_policy.yaml
  - 05_sriov_network_node_policy_placementbinding.yaml
  - 06_sriov_network_node_policy_placementrule.yaml
  - 07_sriov_network_policy.yaml
  - 08_sriov_network_policy_placementbinding.yaml
  - 09_sriov_network_policy_placementrule.yaml
  - 10_slave_ptp_policy.yaml
  - 11_slave_ptp_placementbinding.yaml
  - 12_slave_ptp_placementrule.yaml
